//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Runtime.Serialization;

namespace ApiExc
{
	[Serializable]
	internal class eption : Exception
	{
		private string v;
		private int status_;
		private string text;
		private Dictionary<string, IEnumerable<string>> headers_;
		private object value;

		public eption()
		{
		}

		public eption(string message) : base(message)
		{
		}

		public eption(string message, Exception innerException) : base(message, innerException)
		{
		}

		public eption(string v, int status_, string text, Dictionary<string, IEnumerable<string>> headers_, object value)
		{
			this.v = v;
			this.status_ = status_;
			this.text = text;
			this.headers_ = headers_;
			this.value = value;
		}

		protected eption(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
	}
}