// <auto-generated />
using System;
using CRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM.Model.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<double?>("Arbitration")
                        .HasColumnType("double precision");

                    b.Property<double?>("Balance")
                        .HasColumnType("double precision");

                    b.Property<string>("CompanyBranches")
                        .HasColumnType("text");

                    b.Property<double?>("CompanyBranchesCount")
                        .HasColumnType("double precision");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("CompanySegmentName")
                        .HasColumnType("text");

                    b.Property<string>("CompanySource")
                        .HasColumnType("text");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress01")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress02")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress03")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress04")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress05")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress06")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress07")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress08")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress09")
                        .HasColumnType("text");

                    b.Property<double?>("EmploeeCount")
                        .HasColumnType("double precision");

                    b.Property<string>("ExtraActivity")
                        .HasColumnType("text");

                    b.Property<string>("ExtraPhoneNumber01")
                        .HasColumnType("text");

                    b.Property<string>("ExtraPhoneNumber02")
                        .HasColumnType("text");

                    b.Property<string>("ExtraPhoneNumber03")
                        .HasColumnType("text");

                    b.Property<string>("ExtraPhoneNumber04")
                        .HasColumnType("text");

                    b.Property<string>("ExtraPhoneNumber05")
                        .HasColumnType("text");

                    b.Property<string>("ExtraPhoneNumber06")
                        .HasColumnType("text");

                    b.Property<string>("ExtraPhoneNumber07")
                        .HasColumnType("text");

                    b.Property<string>("ExtraPhoneNumber08")
                        .HasColumnType("text");

                    b.Property<string>("ExtraPhoneNumber09")
                        .HasColumnType("text");

                    b.Property<string>("FocusLink")
                        .HasColumnType("text");

                    b.Property<string>("FullAddress")
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .HasColumnType("text");

                    b.Property<double?>("IncomeLoss")
                        .HasColumnType("double precision");

                    b.Property<string>("Jobs")
                        .HasColumnType("text");

                    b.Property<string>("KPP")
                        .HasColumnType("text");

                    b.Property<string>("LeasingSubject")
                        .HasColumnType("text");

                    b.Property<string>("LeasingSubjectCategory")
                        .HasColumnType("text");

                    b.Property<string>("MSPList")
                        .HasColumnType("text");

                    b.Property<string>("MainActivity")
                        .HasColumnType("text");

                    b.Property<string>("OGRN")
                        .HasColumnType("text");

                    b.Property<string>("OKPD2")
                        .HasColumnType("text");

                    b.Property<string>("ObtainedLicenses")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PropertyPledge")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RegistrationRegion")
                        .HasColumnType("text");

                    b.Property<double?>("Revenue")
                        .HasColumnType("double precision");

                    b.Property<string>("SiteLink")
                        .HasColumnType("text");

                    b.Property<string>("SpecialTaxRegime")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorFullName")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorINNFL")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorJobTitle")
                        .HasColumnType("text");

                    b.Property<string>("ValueAddedTax")
                        .HasColumnType("text");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.HasIndex("INN")
                        .IsUnique();

                    b.ToTable("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
